Repository abelardog/bootcampar, pull requests merged in 2023-09, with the labels that each got.

#47 add class diagram draft to documentation
  docs/diagrama-de-clases.png
Labels: documentation, Sprint 1

#62 37 tk15 crear modelo de bases de datos
  README.md
  docs/modelo-relacional.mwb
  docs/modelo-relacional.png
Labels: documentation

#83 add use case, review
  docs/caso-de-uso-calificar.png
Labels: documentation

#91 update class diagram with methods
  docs/diagrama-de-clases.png
Labels: documentation

#96 95 tk32 actividad inicio de sesion
  app/src/main/java/com/ar/bootcampar/MainActivity.java
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#101 Compile fix
  app/build.gradle.kts
  app/src/main/res/values-night/themes.xml
  build.gradle.kts
Labels: enhancement

#102 Home redirect
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
Labels: enhancement

#104 Features/recuperar la clave
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ResetPasswordActivity.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#107 Feature/fix use cases
  docs/Caso de Uso-Ingresar a la app.pdf
  docs/Caso de Uso.docx
  docs/Caso de uso Hacer curso.drawio.png
  docs/CasoDeUsoListadoDeCursos2.jpg
  docs/Diagrama caso de usos marcar curso favorito.png
  docs/breve-descripcion-de-casos-de-uso.docx
  docs/caso-de-uso-ingresar.png
  docs/caso-de-uso-inscribirse.png
  docs/caso-de-uso-listar-cursos.jpg
  docs/caso-de-uso-marcar-como-favorito.png
  docs/caso-de-uso-registracion.png
  docs/diagrama-de-casos-de-uso-general.pdf
  docs/diagrama-de-casos-de-uso-general.png
  docs/ieee830-bootcampar.pdf
Labels: documentation

#109 Feature/registration use
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ResetPasswordActivity.java
  app/src/main/res/layout/activity_reg.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#112 Feature/main activity
  app/src/main/res/drawable/header_logo.png
  app/src/main/res/layout/activity_main.xml
Labels: enhancement

#116 Connect profile edit
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ar/bootcampar/activities/EditProfileActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ui/profile/ProfileFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditProfile.java
  app/src/main/java/com/ar/bootcampar/fragments/EditProfileViewModel.java
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: enhancement

#120 Feature/readme formating
  README.md
Labels: documentation

#121 add sqlite db script
  docs/db-sqlite.sql
Labels: documentation

#125 add navigation icon for course list
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#126 remove unused code
  app/src/main/java/com/ar/bootcampar/activities/ui/help/HelpFragment.java
Labels: enhancement

#133 tk31 crear actividades de la app
  app/build.gradle.kts
  app/src/main/java/com/ar/bootcampar/fragments/CourseListFragment.java
  app/src/main/res/drawable-hdpi/ic_menu.png
  app/src/main/res/drawable-mdpi/ic_menu.png
  app/src/main/res/drawable-xhdpi/ic_menu.png
  app/src/main/res/drawable-xxhdpi/ic_menu.png
  app/src/main/res/drawable-xxxhdpi/ic_menu.png
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/content_course_list.xml
  app/src/main/res/layout/fragment_course_list.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#136 Feature/129 tk40 implementar actualizar
  app/src/main/java/com/ar/bootcampar/activities/EditProfileActivity.java
  app/src/main/res/layout/activity_reg.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#135 Feature/130 tk41 click en detalles
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/CourseListActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ui/home/HomeFragment.java
  app/src/main/java/com/ar/bootcampar/model/Course.java
  app/src/main/java/com/ar/bootcampar/model/RecentlyAddedAdapter.java
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#139 Contact fragment
  app/src/main/java/com/ar/bootcampar/fragments/ContactFragment.java
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#141 use factory to fill courses
  app/src/main/java/com/ar/bootcampar/fragments/CourseListFragment.java
Labels: enhancement

#149 Feature/video list player
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/CourseVideoActivity.java
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/res/layout/activity_video_list.xml
Labels: enhancement

#147 Feature/token button
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/res/layout/activity_reg.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#146 110 tk37 crear actividad de ayuda faq
  app/src/main/res/layout/fragment_help.xml
Labels: enhancement

#153 Search
  app/src/main/java/com/ar/bootcampar/fragments/SearchFragment.java
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#156 use Leo's link
  README.md
Labels: documentation
