Repository abelardog/bootcampar, pull requests merged in 2023-10, with the labels that each got.

#166 Implementación de base de datos
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ar/bootcampar/MainActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ResetPasswordActivity.java
  app/src/main/java/com/ar/bootcampar/model/CursorHelper.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/Division.java
  app/src/main/java/com/ar/bootcampar/model/Grupo.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/model/Rol.java
  app/src/main/java/com/ar/bootcampar/model/User.java
  app/src/main/java/com/ar/bootcampar/model/Usuario.java
  app/src/main/res/layout/fragment_help.xml
  app/src/main/res/values/strings.xml
  docs/db-sqlite.sql
Labels: enhancement

#215 Feature/ambc categories
  app/src/main/java/com/ar/bootcampar/model/Categoria.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/Grupo.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
Labels: enhancement

#216 Agregar pruebas unitarias para el modelo de Usuario
  app/src/main/java/com/ar/bootcampar/model/CursorHelper.java
  app/src/main/java/com/ar/bootcampar/model/CursorWrapper.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/Division.java
  app/src/main/java/com/ar/bootcampar/model/Grupo.java
  app/src/main/java/com/ar/bootcampar/model/ICursorWrapper.java
  app/src/main/java/com/ar/bootcampar/model/ISQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/SQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/Usuario.java
  app/src/test/java/com/ar/bootcampar/UsuarioDebe.java
Labels: enhancement

#231 Feature/crear usuario test
  app/src/main/java/com/ar/bootcampar/model/ContentValuesWrapper.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IContentValuesWrapper.java
  app/src/main/java/com/ar/bootcampar/model/ISQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/SQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/Usuario.java
  app/src/test/java/com/ar/bootcampar/CrearUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/ExampleUnitTest.java
  app/src/test/java/com/ar/bootcampar/UsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/support/Constants.java
  app/src/test/java/com/ar/bootcampar/support/ContentValuesSpy.java
  app/src/test/java/com/ar/bootcampar/support/SqliteDatabaseWrapperSpy.java
  app/src/test/java/com/ar/bootcampar/support/TestableDatabase.java
Labels: enhancement

#232 197 tk74 agregar visual para crear un curso
  app/src/main/res/layout/fragment_create_course.xml
Labels: enhancement

#233 Agregar pruebas unitarias para borrar usuarios
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/test/java/com/ar/bootcampar/BorrarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/CrearUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/support/SqliteDatabaseWrapperSpy.java
Labels: enhancement

#239 ABMC de lecciones
  app/src/main/java/com/ar/bootcampar/model/Course.java
  app/src/main/java/com/ar/bootcampar/model/CursorWrapper.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/ICursorWrapper.java
  app/src/main/java/com/ar/bootcampar/model/Leccion.java
  app/src/main/java/com/ar/bootcampar/model/utilities/Guardia.java
  app/src/test/java/com/ar/bootcampar/LeccionDebe.java
  app/src/test/java/com/ar/bootcampar/support/Constants.java
Labels: enhancement

#238 174 tk53 crear metodos abmc de grupos
  app/src/main/java/com/ar/bootcampar/model/Database.java
Labels: enhancement

#237 Agregar pruebas unitarias para modificar usuarios
  app/src/test/java/com/ar/bootcampar/ModificarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/support/SqliteDatabaseWrapperSpy.java
Labels: enhancement

#236 Pruebas unitarias para búsqueda de usuario en base de datos
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/test/java/com/ar/bootcampar/BorrarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/support/Constants.java
  app/src/test/java/com/ar/bootcampar/support/CursorWrapperStub.java
  app/src/test/java/com/ar/bootcampar/support/SqliteDatabaseWrapperSpy.java
  app/src/test/java/com/ar/bootcampar/support/TestableDatabase.java
Labels: enhancement

#240 add override methods for unit tests
  app/src/test/java/com/ar/bootcampar/support/CursorWrapperStub.java
Labels: enhancement

#234 add test to pipeline
  .github/workflows/android.yml
  README.md
  app/src/main/java/com/ar/bootcampar/MainActivity.java
Labels: enhancement

#246 Feature/database simplification
  app/src/main/java/com/ar/bootcampar/model/Database.java
Labels: enhancement

#247 Database refactor
  .github/workflows/android.yml
  app/src/main/java/com/ar/bootcampar/model/Database.java
Labels: enhancement

#249 Inscription search 2
  app/src/main/java/com/ar/bootcampar/model/CursorHelper.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/test/java/com/ar/bootcampar/BorrarInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/CrearGrupoDebe.java
  app/src/test/java/com/ar/bootcampar/CrearInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/CrearUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/GrupoDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/support/Constants.java
Labels: enhancement

#263 Fixs ABMC de Cursos
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
Labels: enhancement

#279 Implementar navegación para admin
  app/build.gradle.kts
  app/src/main/java/com/ar/bootcampar/activities/HomeActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCategoriesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCurriculumsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditGroupsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/services/SharedPreferencesManager.java
  app/src/main/res/drawable/baseline_edit_24.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/fragment_edit_categories.xml
  app/src/main/res/layout/fragment_edit_courses.xml
  app/src/main/res/layout/fragment_edit_curriculums.xml
  app/src/main/res/layout/fragment_edit_groups.xml
  app/src/main/res/layout/fragment_edit_lessons.xml
  app/src/main/res/menu/bottom_nav_menu_admin.xml
  app/src/main/res/menu/bottom_nav_menu_student.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#280 Login service
  app/src/main/java/com/ar/bootcampar/activities/HomeActivity.java
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/model/Rol.java
  app/src/main/res/layout/activity_home.xml
Labels: enhancement

#291 Pruebas unitarias para registración
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ResetPasswordActivity.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/model/utilities/Tupla.java
  app/src/test/java/com/ar/bootcampar/RegistracionDebe.java
  app/src/test/java/com/ar/bootcampar/support/TestableLogicServices.java
Labels: enhancement

#293 Feature/creacion grupo
  app/src/main/java/com/ar/bootcampar/fragments/EditGroupsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/GruposListAdapter.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/res/layout/fragment_edit_groups.xml
  app/src/main/res/layout/group_list_item.xml
  app/src/main/res/menu/crud_item_context_menu.xml
Labels: enhancement

#298 193 tk70 cargar informacion de perfil en editprofileactivity
  app/src/main/java/com/ar/bootcampar/activities/EditProfileActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ui/profile/ProfileFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditProfile.java
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: enhancement

#297 take information for contact info from logged in user
  app/src/main/java/com/ar/bootcampar/fragments/ContactFragment.java
Labels: enhancement

#294 Feature/creacion categorias
  app/src/main/java/com/ar/bootcampar/fragments/EditCategoriesFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/services/CategoriasListAdapter.java
  app/src/main/res/layout/category_list_item.xml
  app/src/main/res/layout/fragment_edit_categories.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
Labels: enhancement

#296 make all 10 menu fragments top level
  app/src/main/java/com/ar/bootcampar/activities/HomeActivity.java
Labels: enhancement

#295 Feature/creacion lecciones
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/services/CursosSpinnerAdapter.java
  app/src/main/java/com/ar/bootcampar/services/LeccionesListAdapter.java
  app/src/main/res/layout/course_spinner_item.xml
  app/src/main/res/layout/fragment_edit_lessons.xml
  app/src/main/res/layout/lesson_list_item.xml
Labels: enhancement

#299 Feature/creacion curso
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/model/Curso.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/services/CursosListAdapter.java
  app/src/main/res/layout/course_list_item.xml
  app/src/main/res/layout/fragment_edit_courses.xml
  app/src/test/java/com/ar/bootcampar/BuscarInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/InscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/LeccionDebe.java
  app/src/test/java/com/ar/bootcampar/support/Constants.java
  app/src/test/java/com/ar/bootcampar/support/DummyMaker.java
Labels: enhancement

#301 Misc fixes
  app/src/main/java/com/ar/bootcampar/activities/ui/home/HomeFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/services/CourseAdapter.java
  app/src/main/java/com/ar/bootcampar/services/LeccionesListAdapter.java
  app/src/test/java/com/ar/bootcampar/BuscarInscripcionDebe.java
Labels: enhancement

#303 Feature/creacion curricula
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCurriculumsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/services/CurriculasListAdapter.java
  app/src/main/java/com/ar/bootcampar/services/CursosSpinnerAdapter.java
  app/src/main/java/com/ar/bootcampar/services/SpinnerAdapter.java
  app/src/main/res/layout/curriculum_list_item.xml
  app/src/main/res/layout/fragment_edit_courses.xml
  app/src/main/res/layout/fragment_edit_curriculums.xml
  app/src/main/res/layout/spinner_item.xml
Labels: enhancement

#306 272 tk113 implementar inscripcion a curso
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/CourseListActivity.java
  app/src/main/java/com/ar/bootcampar/activities/FirstFragment.java
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ResetPasswordActivity.java
  app/src/main/java/com/ar/bootcampar/activities/SecondFragment.java
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ui/home/HomeFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/ContactFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/CourseListFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCurriculumsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Categoria.java
  app/src/main/java/com/ar/bootcampar/model/Curricula.java
  app/src/main/java/com/ar/bootcampar/model/Curso.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/Inscripcion.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/model/RecentlyAddedAdapter.java
  app/src/main/java/com/ar/bootcampar/model/Rol.java
  app/src/main/java/com/ar/bootcampar/model/SQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/ContentValuesWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/CursorHelper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/CursorWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/IContentValuesWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/ICursorWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/ISQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/IntentConstants.java
  app/src/main/java/com/ar/bootcampar/services/CourseAdapter.java
  app/src/main/java/com/ar/bootcampar/services/CurriculasListAdapter.java
  app/src/main/java/com/ar/bootcampar/services/CursosListAdapter.java
  app/src/main/java/com/ar/bootcampar/services/LeccionesListAdapter.java
  app/src/main/res/layout/fragment_first.xml
  app/src/main/res/layout/fragment_second.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/ar/bootcampar/BorrarCursoDebe.java
  app/src/test/java/com/ar/bootcampar/BorrarGrupoDebe.java
  app/src/test/java/com/ar/bootcampar/BorrarInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/BorrarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/CrearCursoDebe.java
  app/src/test/java/com/ar/bootcampar/CrearGrupoDebe.java
  app/src/test/java/com/ar/bootcampar/CrearInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/CrearUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/CursoDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarCursoDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarGrupoDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarInscripcionDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/RegistracionDebe.java
  app/src/test/java/com/ar/bootcampar/support/ContentValuesSpy.java
  app/src/test/java/com/ar/bootcampar/support/CursorWrapperStub.java
  app/src/test/java/com/ar/bootcampar/support/SqliteDatabaseWrapperSpy.java
  app/src/test/java/com/ar/bootcampar/support/TestableDatabase.java
Labels: enhancement

#307 creando el logo de la app
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: enhancement

#313 Fix inscripcion
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
Labels: bug, enhancement

#314 Video list entry
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/java/com/ar/bootcampar/fragments/GruposListAdapter.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/services/LeccionAdapter.java
  app/src/main/res/layout/activity_video_list.xml
  app/src/main/res/layout/video_item.xml
Labels: enhancement

#320 Botones perfil
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_profile.xml
Labels: enhancement

#323 Video activity
  app/src/main/java/com/ar/bootcampar/activities/CourseVideoActivity.java
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/java/com/ar/bootcampar/model/utilities/IntentConstants.java
  app/src/main/java/com/ar/bootcampar/services/LeccionAdapter.java
  app/src/main/res/layout/activity_course_video.xml
  app/src/main/res/layout/video_item.xml
Labels: enhancement

#328 Link for lesson
  app/build.gradle.kts
  app/src/main/java/com/ar/bootcampar/activities/CourseVideoActivity.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/Leccion.java
  app/src/main/res/layout/activity_course_video.xml
  app/src/main/res/layout/fragment_edit_lessons.xml
  app/src/test/java/com/ar/bootcampar/LeccionDebe.java
  app/src/test/java/com/ar/bootcampar/support/Constants.java
Labels: enhancement

#332 327 tk133 listado de videos no se ve bien
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/res/layout/activity_video_list.xml
  app/src/main/res/layout/video_item.xml
Labels: bug

#335 make phone number optional, make other read-only
  app/src/main/java/com/ar/bootcampar/fragments/ContactFragment.java
Labels: enhancement

#334 add extra course
  app/src/main/java/com/ar/bootcampar/model/Database.java
Labels: enhancement

#333 Change navigation
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/fragment_edit_lessons.xml
Labels: enhancement

#338 Clean up
  app/src/main/java/com/ar/bootcampar/MainActivity.java
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/CourseListActivity.java
  app/src/main/java/com/ar/bootcampar/activities/CourseVideoActivity.java
  app/src/main/java/com/ar/bootcampar/activities/EditProfileActivity.java
  app/src/main/java/com/ar/bootcampar/activities/HomeActivity.java
  app/src/main/java/com/ar/bootcampar/activities/RegisterActivity.java
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ui/help/HelpFragment.java
  app/src/main/java/com/ar/bootcampar/activities/ui/help/HelpViewModel.java
  app/src/main/java/com/ar/bootcampar/activities/ui/home/HomeFragment.java
  app/src/main/java/com/ar/bootcampar/activities/ui/home/HomeViewModel.java
  app/src/main/java/com/ar/bootcampar/activities/ui/profile/ProfileFragment.java
  app/src/main/java/com/ar/bootcampar/activities/ui/profile/ProfileViewModel.java
  app/src/main/java/com/ar/bootcampar/fragments/EditProfile.java
  app/src/main/java/com/ar/bootcampar/fragments/EditProfileViewModel.java
  app/src/main/java/com/ar/bootcampar/model/Categoria.java
  app/src/main/java/com/ar/bootcampar/model/Categorizacion.java
  app/src/main/java/com/ar/bootcampar/model/Curso.java
  app/src/main/java/com/ar/bootcampar/model/Grupo.java
  app/src/main/java/com/ar/bootcampar/model/Inscripcion.java
  app/src/main/java/com/ar/bootcampar/model/Leccion.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/model/RecentlyAddedAdapter.java
  app/src/main/java/com/ar/bootcampar/model/SQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/Guardia.java
  app/src/main/java/com/ar/bootcampar/model/utilities/ISQLiteDatabaseWrapper.java
  app/src/main/java/com/ar/bootcampar/model/utilities/IntentConstants.java
  app/src/main/java/com/ar/bootcampar/services/LeccionAdapter.java
  app/src/main/java/com/ar/bootcampar/services/SharedPreferencesManager.java
  app/src/main/res/values/strings.xml
Labels: enhancement

#341 change button text if already enrolled
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#340 Unit tests
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/test/java/com/ar/bootcampar/BorrarCategoriaDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarCategoriaDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarCursoDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarDivisionDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarGrupoDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarLeccionDebe.java
  app/src/test/java/com/ar/bootcampar/BuscarUsuarioDebe.java
  app/src/test/java/com/ar/bootcampar/CrearCategoriaDebe.java
  app/src/test/java/com/ar/bootcampar/CrearCursoDebe.java
  app/src/test/java/com/ar/bootcampar/CrearLeccionDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarCategoriaDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarCursoDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarDivisionDebe.java
  app/src/test/java/com/ar/bootcampar/ModificarLeccionDebe.java
  app/src/test/java/com/ar/bootcampar/support/TestChecker.java
Labels: enhancement

#343 Auth0 login
  app/build.gradle.kts
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#345 Feature/rating
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/HomeActivity.java
  app/src/main/java/com/ar/bootcampar/activities/VideoListActivity.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/RatingFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/java/com/ar/bootcampar/model/utilities/IntentConstants.java
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/activity_video_list.xml
  app/src/main/res/layout/fragment_rating.xml
Labels: enhancement

#388 remove unnecessary closing tag
  app/src/main/res/layout/fragment_course_list.xml
Labels: enhancement

#395 357 tk140 el botón de ingresar en el login es muy chico
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#396 content description de logo
  app/src/main/res/layout/fragment_create_lessons.xml
Labels: enhancement

#397 366 tk149 modificar layout params para permitir expansión de texto 1
  app/src/main/res/layout/activity_reset_password.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#398 correccion
  app/src/main/res/layout/activity_reset_password.xml
Labels: enhancement

#399 tamano
  app/src/main/res/layout/category_list_item.xml
Labels: enhancement

#405 Agregando recursos de texto a fragment List
  app/src/main/res/layout/fragment_course_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#406 386 tk169 agregar content description a la imagen en recently added coursexml
  app/src/main/res/layout/recently_added_course.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#413 387 tk170 pasar todos los hardcoded texts de todos los recursos a stringsxml 1
  app/src/main/res/layout/activity_course_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_video_list.xml
  app/src/main/res/layout/content_course_list.xml
  app/src/main/res/layout/curriculum_list_item.xml
  app/src/main/res/layout/fragment_create_course.xml
  app/src/main/res/layout/fragment_create_lessons.xml
  app/src/main/res/layout/fragment_edit_categories.xml
  app/src/main/res/layout/fragment_edit_curriculums.xml
  app/src/main/res/layout/fragment_edit_groups.xml
  app/src/main/res/layout/fragment_edit_lessons.xml
  app/src/main/res/layout/fragment_help.xml
  app/src/main/res/layout/group_list_item.xml
  app/src/main/res/layout/lesson_list_item.xml
  app/src/main/res/layout/video_item.xml
  app/src/main/res/menu/crud_item_context_menu.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#419 Fuente perfil
  app/src/main/java/com/ar/bootcampar/activities/EditProfileActivity.java
  app/src/main/java/com/ar/bootcampar/activities/ui/profile/ProfileFragment.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/res/layout/fragment_edit_profile.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#422 do not disable edittext to update value
  app/src/main/java/com/ar/bootcampar/fragments/ContactFragment.java
Labels: bug

#428 fix name height
  app/src/main/res/layout/fragment_profile.xml
Labels: bug

#426 fix course list refreshing
  app/src/main/java/com/ar/bootcampar/fragments/CourseListFragment.java
Labels: bug

#425 fix inscription button not refreshing
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
Labels: bug

#424 Accesibilidad de la App
  docs/testing/accesibilidad (1).pdf
Labels: documentation

#429 Delete unused courses
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/res/drawable/csharp.png
Labels: enhancement

#435 Update sql script
  docs/db-mysql.sql
  docs/db-sqlite.sql
  docs/diagrama-entidad-relacion.png
  docs/modelo-relacional.mwb
  docs/modelo-relacional.png
Labels: documentation

#434 tk154 agregar speakable text para favoritos
  app/src/main/res/layout/content_course_list.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#433 tk160 agregar autofill al edit category description
  app/src/main/java/com/ar/bootcampar/fragments/EditCategoriesFragment.java
  app/src/main/res/layout/category_list_item.xml
  app/src/main/res/layout/fragment_edit_categories.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#439 fix inscription rating refresh
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
Labels: bug

#438 fix for logging with github account
  app/src/main/java/com/ar/bootcampar/activities/LoginActivity.java
Labels: bug

#437 move maquetado to docs directory
  docs/maquetado/Captura de pantalla 2023-09-07 192414.png
  docs/maquetado/Captura de pantalla 2023-09-07 194043.png
  docs/maquetado/Captura de pantalla 2023-09-07 194533.png
  docs/maquetado/Captura de pantalla 2023-09-07 200634.png
Labels: documentation

#436 Class diagram update
  docs/diagrama-de-clases-expandido.png
  docs/diagrama-de-clases.drawio
  docs/diagrama-de-clases.png
Labels: documentation

#447 content description a estrellas
  app/src/main/res/layout/activity_video_list.xml
Labels: enhancement

#450 Agregar categorizacion al crear cursos
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/res/layout/fragment_edit_courses.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#451 Admin inscription
  app/src/main/java/com/ar/bootcampar/activities/CourseDetailActivity.java
  app/src/main/java/com/ar/bootcampar/activities/HomeActivity.java
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/navigation/mobile_navigation_admin.xml
Labels: enhancement

#454 update readme files
  README.md
  docs/testing/README.md
Labels: documentation

#456 Last changes
  app/src/main/java/com/ar/bootcampar/fragments/EditCategoriesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCurriculumsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditGroupsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/res/menu/crud_item_context_menu_delete.xml
Labels: enhancement

#457 Completar modificaciones
  app/src/main/java/com/ar/bootcampar/fragments/EditCategoriesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCoursesFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditCurriculumsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditGroupsFragment.java
  app/src/main/java/com/ar/bootcampar/fragments/EditLessonsFragment.java
  app/src/main/java/com/ar/bootcampar/model/Database.java
  app/src/main/java/com/ar/bootcampar/model/IDatabase.java
  app/src/main/java/com/ar/bootcampar/model/LogicServices.java
  app/src/main/res/menu/crud_item_context_menu_delete.xml
Labels: enhancement
